var = input('Type something:')
print('Type: ', type(var) )
print('Alphanumeric: ', var.isalnum ())
print('Only alphabetical: ', var.isalpha ())
print('Only numeric: ', var.isnumeric ())
print('Default ASCII: ', var.isascii ())
print('Decimal: ', var.isdecimal ())
print('Valid identifier of variable: ', var.isidentifier ())
print('Only lower: ', var.islower ())
print('Only upper: ', var.isupper ())
print('Printable: ', var.isprintable ())
print('Only spaces: ', var.isspace ())
print('Title: ', var.istitle ())
